name: integration tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pip-requirements: "requirements-1.0.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.1.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.2.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.2.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.3.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.3.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.4.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.4.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.4.txt"
            python-version: "3.11"
          - pip-requirements: "requirements-1.5.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.5.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.5.txt"
            python-version: "3.11"
          - pip-requirements: "requirements-1.6.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.6.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.6.txt"
            python-version: "3.11"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: pip
      - name: "Install dependencies"
        working-directory: "${{ github.workspace }}"
        run: |
          python -m pip install --upgrade pip==23.1.0
          pip install -r requirements-dev.txt
      - name: "Install dbt Packages"
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt deps --profiles-dir "${{ github.workspace }}/integration_tests/profiles"
      - name: validate
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt ls --profiles-dir "${{ github.workspace }}/integration_tests/profiles"
