name: integration tests

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "**/*.md"

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      INTEGRATION_TESTS_PROJECT: "dummy-project"
    strategy:
      fail-fast: false
      matrix:
        include:
          - pip-requirements: "requirements-1.5.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.5.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.5.txt"
            python-version: "3.11"
          - pip-requirements: "requirements-1.6.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.6.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.6.txt"
            python-version: "3.11"
          - pip-requirements: "requirements-1.7.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.7.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.7.txt"
            python-version: "3.11"
          - pip-requirements: "requirements-1.8.txt"
            python-version: "3.9"
          - pip-requirements: "requirements-1.8.txt"
            python-version: "3.10"
          - pip-requirements: "requirements-1.8.txt"
            python-version: "3.11"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: |
            requirements-dev.txt
      - name: "Install dependencies"
        working-directory: "${{ github.workspace }}"
        run: |
          python -m pip install --upgrade pip==24.3
          pip install -r requirements-dev.txt
      - name: "Install dbt Packages"
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt deps --profiles-dir "${{ github.workspace }}/integration_tests/profiles"
      - name: validate
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          dbt ls --profiles-dir "${{ github.workspace }}/integration_tests/profiles" \
              --vars "$(cat "${{ github.workspace }}/integration_tests/vars/github-actions.yml")"
